create table sys_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    real_name varchar(64) not null,
    user_type varchar(20) not null check (user_type in ('STUDENT', 'TEACHER', 'STAFF')),
    department varchar(100),
    email varchar(128),
    phone varchar(32),
    status varchar(20) not null default 'ACTIVE' check (status in ('ACTIVE', 'DISABLED', 'LOCKED')),
    must_change_password boolean not null default true,
    failed_login_count integer not null default 0 check (failed_login_count >= 0),
    locked_until timestamptz,
    booking_frozen_until timestamptz,
    no_show_count integer not null default 0 check (no_show_count >= 0),
    session_version integer not null default 0 check (session_version >= 0),
    version bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table sys_permission (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    name varchar(100) not null
);

create table sys_role (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    name varchar(80) not null,
    description varchar(255),
    built_in boolean not null default false,
    version bigint not null default 0
);

create table sys_role_permission (
    role_id bigint not null references sys_role(id) on delete cascade,
    permission_id bigint not null references sys_permission(id) on delete cascade,
    primary key (role_id, permission_id)
);

create table sys_user_role (
    user_id bigint not null references sys_user(id) on delete cascade,
    role_id bigint not null references sys_role(id) on delete cascade,
    primary key (user_id, role_id)
);

create table course_period (
    period_no smallint primary key check (period_no between 1 and 4),
    name varchar(40) not null,
    start_time time not null,
    end_time time not null,
    enabled boolean not null default true,
    version bigint not null default 0,
    updated_at timestamptz not null default now(),
    check (start_time < end_time)
);

create table lab (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    name varchar(100) not null,
    building varchar(100) not null,
    room_no varchar(40) not null,
    capacity integer not null check (capacity > 0),
    lab_type varchar(60) not null,
    description text,
    image_url varchar(500),
    responsible_user_id bigint references sys_user(id),
    tags jsonb not null default '[]'::jsonb check (jsonb_typeof(tags) = 'array'),
    status varchar(20) not null default 'ACTIVE' check (status in ('ACTIVE', 'DISABLED', 'MAINTENANCE')),
    student_approval_mode varchar(20) not null default 'MANUAL' check (student_approval_mode in ('AUTO', 'MANUAL')),
    teacher_approval_mode varchar(20) not null default 'MANUAL' check (teacher_approval_mode in ('AUTO', 'MANUAL')),
    allow_student_booking boolean not null default true,
    max_periods_per_user_day integer not null default 2 check (max_periods_per_user_day between 1 and 4),
    advance_days integer not null default 14 check (advance_days >= 0),
    cancel_before_minutes integer not null default 120 check (cancel_before_minutes >= 0),
    require_check_in boolean not null default true,
    version bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (building, room_no)
);

create table lab_manager (
    lab_id bigint not null references lab(id) on delete cascade,
    user_id bigint not null references sys_user(id) on delete cascade,
    primary key (lab_id, user_id)
);

create table lab_open_rule (
    id bigint generated by default as identity primary key,
    lab_id bigint not null references lab(id) on delete cascade,
    day_of_week smallint not null check (day_of_week between 1 and 7),
    period_no smallint not null references course_period(period_no),
    valid_from date,
    valid_to date,
    created_at timestamptz not null default now(),
    check (valid_to is null or valid_from is null or valid_from <= valid_to),
    unique nulls not distinct (lab_id, day_of_week, period_no, valid_from, valid_to)
);

create table lab_blackout (
    id bigint generated by default as identity primary key,
    lab_id bigint not null references lab(id) on delete cascade,
    booking_date date not null,
    period_no smallint not null references course_period(period_no),
    reason varchar(255) not null,
    created_by bigint not null references sys_user(id),
    created_at timestamptz not null default now(),
    unique (lab_id, booking_date, period_no)
);

create table equipment (
    id bigint generated by default as identity primary key,
    lab_id bigint not null references lab(id),
    asset_code varchar(64) not null unique,
    category varchar(80) not null,
    name varchar(100) not null,
    model varchar(100),
    total_quantity integer not null default 1 check (total_quantity > 0),
    required_qualification varchar(100),
    status varchar(20) not null default 'AVAILABLE' check (status in ('AVAILABLE', 'MAINTENANCE', 'RETIRED')),
    version bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table user_qualification (
    user_id bigint not null references sys_user(id) on delete cascade,
    qualification_code varchar(100) not null,
    valid_until date,
    granted_by bigint references sys_user(id),
    granted_at timestamptz not null default now(),
    primary key (user_id, qualification_code)
);

create table reservation (
    id bigint generated by default as identity primary key,
    reservation_no varchar(32) not null unique,
    applicant_id bigint not null references sys_user(id),
    applicant_type varchar(16) not null check (applicant_type in ('STUDENT', 'TEACHER')),
    lab_id bigint not null references lab(id),
    title varchar(120) not null,
    purpose text not null,
    participant_count integer not null check (participant_count > 0),
    booking_date date not null,
    period_no smallint not null references course_period(period_no),
    status varchar(24) not null check (status in ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', 'IN_USE', 'COMPLETED', 'NO_SHOW')),
    contact_phone varchar(32) not null,
    project_or_course varchar(120) not null,
    remark text,
    cancellation_reason text,
    approved_by bigint references sys_user(id),
    approved_at timestamptz,
    checked_in_at timestamptz,
    checked_out_at timestamptz,
    version bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index uk_reservation_effective_slot
    on reservation (lab_id, booking_date, period_no)
    where status in ('APPROVED', 'IN_USE', 'COMPLETED');

create table reservation_equipment (
    reservation_id bigint not null references reservation(id) on delete cascade,
    equipment_id bigint not null references equipment(id),
    quantity integer not null check (quantity > 0),
    primary key (reservation_id, equipment_id)
);

create table approval_record (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null references reservation(id),
    approver_id bigint not null references sys_user(id),
    action varchar(24) not null check (action in ('APPROVE', 'REJECT', 'ADMIN_CANCEL')),
    from_status varchar(24) not null,
    to_status varchar(24) not null,
    comment text,
    idempotency_key varchar(128),
    created_at timestamptz not null default now(),
    unique (approver_id, idempotency_key)
);

create table reservation_status_history (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null references reservation(id),
    from_status varchar(24),
    to_status varchar(24) not null,
    reason text,
    operator_id bigint references sys_user(id),
    source varchar(24) not null check (source in ('USER', 'ADMIN', 'AUTO_APPROVAL', 'SCHEDULER')),
    created_at timestamptz not null default now()
);

create table attendance_record (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null unique references reservation(id),
    check_in_at timestamptz,
    check_out_at timestamptz,
    check_in_method varchar(20),
    check_out_method varchar(20),
    operated_by bigint references sys_user(id),
    actual_participant_count integer check (actual_participant_count is null or actual_participant_count >= 0),
    note varchar(500),
    version bigint not null default 0,
    check (check_out_at is null or check_in_at is null or check_in_at <= check_out_at)
);

create table user_violation (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id),
    reservation_id bigint references reservation(id),
    violation_type varchar(32) not null check (violation_type in ('NO_SHOW', 'MISUSE', 'DAMAGE', 'OTHER')),
    description varchar(500) not null,
    points integer not null default 1 check (points > 0),
    created_by bigint references sys_user(id),
    created_at timestamptz not null default now()
);

create table refresh_session (
    id uuid primary key,
    user_id bigint not null references sys_user(id) on delete cascade,
    token_hash varchar(64) not null unique,
    session_family_id uuid not null,
    user_session_version integer not null,
    issued_at timestamptz not null,
    expires_at timestamptz not null,
    last_used_at timestamptz,
    revoked_at timestamptz,
    revoke_reason varchar(80),
    replaced_by uuid references refresh_session(id),
    user_agent varchar(500),
    ip_address inet,
    check (issued_at < expires_at)
);

create table notification (
    id bigint generated by default as identity primary key,
    recipient_id bigint not null references sys_user(id) on delete cascade,
    notification_type varchar(40) not null,
    title varchar(120) not null,
    content text not null,
    related_type varchar(40),
    related_id bigint,
    read_at timestamptz,
    created_at timestamptz not null default now()
);

create table outbox_event (
    id uuid primary key,
    aggregate_type varchar(60) not null,
    aggregate_id varchar(80) not null,
    event_type varchar(80) not null,
    payload jsonb not null check (jsonb_typeof(payload) = 'object'),
    status varchar(20) not null default 'PENDING' check (status in ('PENDING', 'PROCESSING', 'DELIVERED', 'FAILED')),
    retry_count integer not null default 0 check (retry_count >= 0),
    next_attempt_at timestamptz not null default now(),
    claimed_at timestamptz,
    delivered_at timestamptz,
    last_error varchar(1000),
    created_at timestamptz not null default now()
);

create table outbox_delivery_attempt (
    id bigint generated by default as identity primary key,
    event_id uuid not null references outbox_event(id) on delete cascade,
    channel varchar(40) not null,
    attempt_no integer not null check (attempt_no > 0),
    outcome varchar(20) not null check (outcome in ('SUCCESS', 'RETRY', 'FAILED')),
    error_summary varchar(1000),
    attempted_at timestamptz not null default now(),
    unique (event_id, channel, attempt_no)
);

create table audit_log (
    id bigint generated by default as identity primary key,
    actor_id bigint references sys_user(id),
    actor_username varchar(64),
    action varchar(80) not null,
    target_type varchar(60),
    target_id varchar(80),
    request_id varchar(64) not null,
    result varchar(20) not null check (result in ('SUCCESS', 'FAILURE')),
    detail jsonb not null default '{}'::jsonb check (jsonb_typeof(detail) = 'object'),
    ip_address inet,
    created_at timestamptz not null default now()
);

create table idempotency_record (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id) on delete cascade,
    operation varchar(80) not null,
    idempotency_key varchar(128) not null,
    request_hash char(64) not null,
    processing_state varchar(20) not null check (processing_state in ('PROCESSING', 'COMPLETED', 'FAILED')),
    response_status integer,
    response_body jsonb,
    resource_type varchar(60),
    resource_id varchar(80),
    created_at timestamptz not null default now(),
    expires_at timestamptz not null,
    unique (user_id, operation, idempotency_key)
);

create table system_setting (
    setting_key varchar(100) primary key,
    setting_value jsonb not null,
    description varchar(255),
    version bigint not null default 0,
    updated_by bigint references sys_user(id),
    updated_at timestamptz not null default now()
);

create index idx_user_status on sys_user (status);
create index idx_user_role_role on sys_user_role (role_id, user_id);
create index idx_lab_status_building on lab (status, building);
create index idx_lab_tags on lab using gin (tags);
create index idx_open_rule_lookup on lab_open_rule (lab_id, day_of_week, period_no, valid_from, valid_to);
create index idx_blackout_lookup on lab_blackout (lab_id, booking_date, period_no);
create index idx_equipment_lab_status on equipment (lab_id, status);
create index idx_reservation_applicant_created on reservation (applicant_id, created_at desc);
create index idx_reservation_lab_date_period on reservation (lab_id, booking_date, period_no);
create index idx_reservation_status_date on reservation (status, booking_date);
create index idx_reservation_type_date on reservation (applicant_type, booking_date);
create index idx_reservation_equipment_usage on reservation_equipment (equipment_id, reservation_id);
create index idx_history_reservation_created on reservation_status_history (reservation_id, created_at);
create index idx_approval_reservation_created on approval_record (reservation_id, created_at);
create index idx_refresh_user_active on refresh_session (user_id, expires_at) where revoked_at is null;
create index idx_notification_recipient_created on notification (recipient_id, created_at desc);
create index idx_notification_unread on notification (recipient_id, created_at desc) where read_at is null;
create index idx_outbox_claim on outbox_event (status, next_attempt_at, created_at);
create index idx_audit_created on audit_log (created_at desc);
create index idx_audit_actor_action on audit_log (actor_id, action, created_at desc);
create index idx_idempotency_expiry on idempotency_record (expires_at);

insert into sys_permission (id, code, name) values
    (1, 'lab:read', '查询实验室'),
    (2, 'lab:write', '维护实验室'),
    (3, 'equipment:read', '查询设备'),
    (4, 'equipment:write', '维护设备'),
    (5, 'reservation:create', '创建预约'),
    (6, 'reservation:read:self', '查询本人预约'),
    (7, 'reservation:read:managed', '查询管辖预约'),
    (8, 'reservation:approve', '审批预约'),
    (9, 'reservation:cancel:any', '强制取消预约'),
    (10, 'checkin:manage', '管理签到签退'),
    (11, 'statistics:read', '查询统计'),
    (12, 'user:write', '维护用户'),
    (13, 'role:write', '维护角色'),
    (14, 'audit:read', '查询审计'),
    (15, 'settings:write', '维护系统配置');

insert into sys_role (id, code, name, description, built_in) values
    (1, 'STUDENT', '学生', '学生业务身份', true),
    (2, 'TEACHER', '教师', '教师业务身份', true),
    (3, 'LAB_ADMIN', '实验室管理员', '仅管理被授权实验室', true),
    (4, 'SYSTEM_ADMIN', '系统管理员', '全院管理权限', true);

insert into sys_role_permission (role_id, permission_id)
select 1, id from sys_permission where code in ('lab:read', 'equipment:read', 'reservation:create', 'reservation:read:self');
insert into sys_role_permission (role_id, permission_id)
select 2, id from sys_permission where code in ('lab:read', 'equipment:read', 'reservation:create', 'reservation:read:self');
insert into sys_role_permission (role_id, permission_id)
select 3, id from sys_permission where code in ('lab:read', 'lab:write', 'equipment:read', 'equipment:write', 'reservation:read:managed', 'reservation:approve', 'reservation:cancel:any', 'checkin:manage', 'statistics:read');
insert into sys_role_permission (role_id, permission_id)
select 4, id from sys_permission;

insert into course_period (period_no, name, start_time, end_time) values
    (1, '第一大节', '08:00', '09:40'),
    (2, '第二大节', '10:00', '11:40'),
    (3, '第三大节', '14:00', '15:40'),
    (4, '第四大节', '16:00', '17:40');

insert into system_setting (setting_key, setting_value, description) values
    ('attendance.check-in-before-minutes', '15', '允许提前签到分钟数'),
    ('attendance.check-in-grace-minutes', '15', '开始后签到宽限分钟数'),
    ('attendance.auto-complete', 'true', '到期自动完成'),
    ('violation.no-show-threshold', '3', '触发冻结的爽约次数'),
    ('violation.freeze-days', '30', '爽约冻结天数'),
    ('export.max-rows', '10000', '单次同步 CSV 最大行数');

select setval(pg_get_serial_sequence('sys_permission', 'id'), (select max(id) from sys_permission), true);
select setval(pg_get_serial_sequence('sys_role', 'id'), (select max(id) from sys_role), true);
