spring:
  config:
    activate:
      on-profile: prod
  datasource:
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  security:
    jwt-secret: ${JWT_SECRET}
    cookie-secure: true
server:
  error:
    include-message: never
    include-stacktrace: never
